### ISSUE TITLE
How to deal with "Evaluation timed out" problem?

### ISSUE THREAD

**Issue by doggy8088** [zspitz/ANTLR4ParseTreeVisualizer#62]
If my source too big, how can I still show the ANTLR4 Parse Tree Visualizer?

![image](https://user-images.githubusercontent.com/88981/127415193-50d8d0cd-5a94-410e-970a-fbffacba5c70.png)

```log
   at Microsoft.VisualStudio.DebuggerVisualizers.Impl.VisualizerObjectProvider.TransferDataToDebuggeeSideVisualizer(Stream outgoingData)
   at Microsoft.VisualStudio.DebuggerVisualizers.Impl.VisualizerObjectProvider.Microsoft.VisualStudio.DebuggerVisualizers.IVisualizerObjectProvider.TransferObject(Object outgoingObject)
   at Periscope.VisualizerWindowBase`2.initialize(IVisualizerObjectProvider objectProvider, TConfig config, ConfigDiffStates configDiffState)
   at Periscope.VisualizerWindowBase`2.Initialize(IVisualizerObjectProvider objectProvider, TConfig config)
   at Periscope.VisualizerBase`2.Show(IDialogVisualizerService windowService, IVisualizerObjectProvider objectProvider)
   at ClrCustomVisualizerVSHost.ClrCustomVisualizerVSHostHelper.DisplayValue(IntPtr hWnd, SuccessEvaluationResultProxy evaluationResult, Int32 selectedIndex, DkmApiVersion protocolVersion)
```

**Comment by zspitz** [comment]
As a temporary workaround, you can increase the timeout length; see https://stackoverflow.com/q/787334/111794.

AFAICT with a large tree, the visualizer processes the entire tree, even when the user can only see a fraction of the tree at once. The solution would be to only process part of the tree, and be able to request other parts on demand.

**Comment by zspitz** [comment]
The configuration may be stored in a different place in VS 2019 -- https://stackoverflow.com/questions/41119996/where-does-visual-studio-2017-store-its-config?noredirect=1&lq=1 .

**Comment by MihaMarkic** [comment]
[VS2019] In my case I have a fairly sample grammar and I've seen the error the first time I've tried visualizer on an string. And the error persisted until I restarted VS. Now it works fine.

**Comment by zspitz** [comment]
@MihaMarkic Do you think you could attach the grammar and string to this issue?

@doggy8088 I assume this isn't what you're seeing; you're seeing the same error multiple times, even after having restarted VS. Could you attach a grammar and sample string?

**Comment by doggy8088** [comment]
@zspitz My original grammar quality is pretty low. After rewriting my grammar, all performance issue has been resolved.

**Comment by MihaMarkic** [comment]
@zspitz It was really a simple one taken from tutorial, I think. It most probably isn't important in this case. I've overwritten it since I posted. But if I see the same error again, I'll post the grammar here.

**Comment by zspitz** [comment]
@doggy8088 @MihaMarkic Thanks to you both for reporting and interacting on this issue. It's still a relevant problem, when there's a large parse tree. But I'm going to hold off on this for now, because fixing it is a significant architectural change.
